### ISSUE TITLE
PXCH_CONFIG_EXTRA_SIZE error

### ISSUE THREAD

**Issue by 406436019** [shunf4/proxychains.exe#1]
PXCH_CONFIG_EXTRA_SIZE error!  

The following code is modified by me

#define PXCH_CONFIG_EXTRA_SIZE(pPxchConfig) PXCH_CONFIG_EXTRA_SIZE_BY_N((pPxchConfig)->dwProxyNum, (pPxchConfig)->dwRuleNum, (pPxchConfig)->dwHostsEntryNum)

**Comment by shunf4** [comment]
449819a should fix this.
Please try 0.4.2.
